CREATE TABLE PATIENTS (
  ID           INT AUTO_INCREMENT PRIMARY KEY,
  NAME         VARCHAR(255) NOT NULL,
  IS_MALE       BOOLEAN      NOT NULL,
  BIRTH_DATE    DATE         NOT NULL,
  BIRTH_PLACE   VARCHAR(100),
  PHONE        VARCHAR(20)  NOT NULL,
  EMAIL        VARCHAR(50),
  CITY         VARCHAR(50),
  STREET       VARCHAR(150),
  LAST_MODIFIED TIMESTAMP
);

CREATE INDEX IDX_PATIENT_NAME
  ON patients (name);