CREATE TABLE THERAPIES (
  ID           INT AUTO_INCREMENT PRIMARY KEY,
  THERAPY_DATE DATE NOT NULL,
  THERAPY      VARCHAR(500),
  TREATMENT    VARCHAR(500),
  INTERVIEW    VARCHAR(1500),
  RESULT       VARCHAR(1500),
  PATIENT_ID   INT,
  THERAPIST_ID INT,

  FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID),
  FOREIGN KEY (THERAPIST_ID) REFERENCES THERAPISTS (ID)
);


